steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/preprod-mock:${_TAG}', '.']

  # 2️⃣ Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/preprod-mock:${_TAG}']

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy preprod-mock \
          --image gcr.io/$PROJECT_ID/preprod-mock:${_TAG} \
          --region asia-southeast1 \
          --platform managed \
          --no-allow-unauthenticated \
          --service-account tdg-automation@tdg-automation-gcp.iam.gserviceaccount.com

images:
  - 'gcr.io/$PROJECT_ID/preprod-mock:${_TAG}'

substitutions:
  _TAG: 'manual-test'